--- 
- name: Install Hyper-V Feature
  import_role: 
    name: bsio.iac.roles.hyper_v
    tasks_from: install-hyper-v

- name: Create Hyper-V Virtual Switch
  import_role: 
    name: bsio.iac.roles.hyper_v
    tasks_from: create-virtual-switch

- name: Build Windows Server ISO
  import_tasks: 
    file: build_windows_server_iso.yml

- name: Build Windows Server Template
  import_tasks: 
    name: bsio.iac.roles.hyper_v
    tasks_from: create_windows_server_template.yml