--- 
- name: Install Hyper-V Feature
  import_role: 
    name: bsio.iac.roles.hyper_v
    tasks_from: install_hyper_v

- name: Create Hyper-V Virtual Switch
  import_role: 
    name: bsio.iac.roles.hyper_v
    tasks_from: create_virtual_switch

- name: Build Windows Server ISO
  import_tasks: 
    file: build_windows_server_iso.yml

- name: Build Server Templates
  import_role: 
    name: bsio.iac.roles.hyper_v
    tasks_from: create_server_templates.yml